services:
  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=adminpassword123  # Please change in production
      - DOCKER_INFLUXDB_INIT_ORG=greenhouse_org
      - DOCKER_INFLUXDB_INIT_BUCKET=greenhouse
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=my-super-secret-admin-token
    volumes:
      - influxdb-data:/var/lib/influxdb2
    restart: unless-stopped

  subscriber:
    build:
      context: ./raspberrypi
      dockerfile: Dockerfile
    container_name: mqtt_subscriber
    restart: unless-stopped
    depends_on:
      - influxdb
    env_file:
      - ./raspberrypi/.env
    environment:
      - INFLUXDB_URL=http://influxdb:8086

  detector:
    build:
      context: ./raspberrypi
      dockerfile: Dockerfile
    command: ["python", "-u", "detector.py"]
    container_name: mqtt_detector
    restart: unless-stopped
    depends_on:
      - influxdb
    env_file:
      - ./raspberrypi/.env
    environment:
      - INFLUXDB_URL=http://influxdb:8086

volumes:
  influxdb-data:
